#!/opt/pwn.college/python

import os
import pathlib

from flask import Flask, request

flag = open("/flag").read().strip()
challenge_host = "challenge.localhost"
hacker_host = "hacker.localhost"
app = Flask(__name__)


@app.route("/", methods=["GET", "POST"])
@app.route("/<path:path>", methods=["GET", "POST"])
def challenge(path=""):
    path = request.args.get("path")
    assert path, "Missing `path` argument"
    return (pathlib.Path(app.root_path) / path).read_text()


@app.before_request
def before_request():
    if request.host != challenge_host:
        return "Service Unavailable\n", 503


@app.after_request
def after_request(response):
    response.headers["Server"] = "pwn.college"
    del response.headers["Content-Type"]
    return response


@app.errorhandler(AssertionError)
def assertion_handler(error):
    print(f"{error}\n")
    return f"{error}\n", 400


@app.errorhandler(Exception)
def exception_handler(error):
    import traceback

    print(traceback.format_exc())
    return traceback.format_exc(), 500


def start():
    os.environ.clear()
    os.environ["PATH"] = "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    os.setuid(os.geteuid())

    app.secret_key = flag
    app.run(challenge_host, 80)


start()
